[package]
name = "rebaser"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "rebaser"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
rebaser-server = { path = "../../lib/rebaser-server" }
si-service = { path = "../../lib/si-service" }
si-std = { path = "../../lib/si-std" }
