protoPackageName = "si.aws_eks_cluster_runtime"

service.AwsEksClusterRuntime.GetComponent.query = true
service.AwsEksClusterRuntime.ListComponents.query = true
service.AwsEksClusterRuntime.PickComponent.query = true
service.AwsEksClusterRuntime.CreateEntity.mutation = true
service.AwsEksClusterRuntime.ListEntities.query = true
service.AwsEksClusterRuntime.GetEntity.query = true
service.AwsEksClusterRuntime.SyncEntity.query = true
service.AwsEksClusterRuntime.ListEntityEvents.query = true

[message.Component.integrationId.has_one]
to = "integration"
grpcServiceName = "Account"
method = "GetIntegration"
type = "Integration"

[message.Component.integrationServiceId.has_one]
to = "integrationService"
grpcServiceName = "Account"
method = "GetIntegrationService"
type = "IntegrationService"

[message.Entity.integrationId.has_one]
to = "integration"
grpcServiceName = "Account"
method = "GetIntegration"
type = "Integration"

[message.Entity.integrationServiceId.has_one]
to = "integrationService"
grpcServiceName = "Account"
method = "GetIntegrationService"
type = "IntegrationService"

[message.Entity.workspaceId.has_one]
to = "workspace"
grpcServiceName = "Account"
method = "GetWorkspace"
type = "Workspace"

[message.Entity.organizationId.has_one]
to = "organization"
grpcServiceName = "Account"
method = "GetOrganization"
type = "Organization"

[message.Entity.billingAccountId.has_one]
to = "billingAccount"
grpcServiceName = "Account"
method = "GetBillingAccount"
type = "BillingAccount"

[[message.Entity.id.has_many]]
to = "entityEvents"
grpcServiceName = "AwsEksClusterRuntime"
method = "awsEksClusterRuntimeListEntityEvents"
type = "AwsEksClusterRuntimeListEntityEventsReply"
inputType = "AwsEksClusterRuntimeListEntityEventsRequest"

[message.EntityEvent.entityId.has_one]
to = "entity"
grpcServiceName = "AwsEksClusterRuntime"
method = "GetEntity"
type = "AwsEksClusterRuntimeEntity"

[message.EntityEvent.userId.has_one]
to = "user"
grpcServiceName = "Account"
method = "GetUser"
type = "User"

