[package]
name = "hoist"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
clap = { workspace = true }
color-eyre = { workspace = true }
futures = { workspace = true }
indicatif = { workspace = true }
json-patch = { workspace = true }
module-index-client = { path = "../../lib/module-index-client" }
rand = { workspace = true }
remain = { workspace = true }
serde_json = { workspace = true }
si-pkg = { path = "../../lib/si-pkg" }
tokio = { workspace = true }
ulid = { workspace = true }
url = { workspace = true }
