# NOTE(nick,jacob): adding cargo env. Original vendored file continues below.
cargo_env = true

# vendored-date: 2023-05-03
# project: https://github.com/facebook/buck2
# commit-hash: f24bf491d4ee266e1ccb444919bce598ba88ad8a
# commit-date: 2023-02-21T07:04:43-0800
# source: https://github.com/facebook/buck2/blob/f24bf491d4ee266e1ccb444919bce598ba88ad8a/shim/third-party/rust/fixups/rings/fixups.toml

# Copied from fbsource fixup.

buildscript = []

# Generate a C/C++ build rule for all the C code

[[platform_fixup.'cfg(all(target_arch = "x86_64", target_os = "linux"))'.buildscript]]
[platform_fixup.'cfg(all(target_arch = "x86_64", target_os = "linux"))'.buildscript.cxx_library]
name = "ring-c-asm-elf-x86_84"
srcs = [ "crypto/**/*.c", "pregenerated/*x86_64*-elf.S" ]
headers = [ "include/**/*.h", "crypto/**/*.h", "third_party/**/*.h", "crypto/**/*.inl" ]
# Exclude C AES because we've got the x86_64 one
exclude = [ "crypto/fipsmodule/aes/aes.c" ]
include_paths = ["include"]
compiler_flags = ["-Wno-error"]

[[platform_fixup.'cfg(all(target_arch = "aarch64", target_os = "linux"))'.buildscript]]
[platform_fixup.'cfg(all(target_arch = "aarch64", target_os = "linux"))'.buildscript.cxx_library]
name = "ring-c-asm-elf-aarch64"
srcs = [ "crypto/**/*.c", "pregenerated/*armv8*-linux64.S", "pregenerated/*armx*-linux64.S" ]
headers = [ "include/**/*.h", "crypto/**/*.h", "third_party/**/*.h", "crypto/**/*.inl" ]
exclude = [ "crypto/cpu-intel.c" ]
include_paths = ["include"]
compiler_flags = ["-Wno-error"]

[[platform_fixup.'cfg(all(target_arch = "x86_64", target_os = "macos"))'.buildscript]]
[platform_fixup.'cfg(all(target_arch = "x86_64", target_os = "macos"))'.buildscript.cxx_library]
name = "ring-c-asm-macos-x86_64"
srcs = [ "crypto/**/*.c", "pregenerated/*x86_64*-macosx.S" ]
headers = [ "include/**/*.h", "crypto/**/*.h", "third_party/**/*.h", "crypto/**/*.inl" ]
# Exclude C AES because we've got the x86_64 one
exclude = [ "crypto/fipsmodule/aes/aes.c" ]
include_paths = ["include"]
compiler_flags = ["-Wno-error"]

[[platform_fixup.'cfg(all(target_arch = "aarch64", target_os = "macos"))'.buildscript]]
[platform_fixup.'cfg(all(target_arch = "aarch64", target_os = "macos"))'.buildscript.cxx_library]
name = "ring-c-asm-macos-arm64"
srcs = [ "crypto/**/*.c", "pregenerated/*armv8*-ios64.S", "pregenerated/*armx*-ios64.S" ]
headers = [ "include/**/*.h", "crypto/**/*.h", "third_party/**/*.h", "crypto/**/*.inl" ]
exclude = [ "crypto/cpu-intel.c" ]
include_paths = ["include"]
compiler_flags = ["-Wno-error"]

[[platform_fixup.'cfg(all(target_arch = "x86_64", target_os = "windows"))'.buildscript]]
[platform_fixup.'cfg(all(target_arch = "x86_64", target_os = "windows"))'.buildscript.cxx_library]
name = "ring-c-win-x86_84"
srcs = [ "crypto/**/*.c" ]
headers = [ "include/**/*.h", "crypto/**/*.h", "third_party/**/*.h", "crypto/**/*.inl" ]
# Exclude C AES because we've got the x86_64 one
exclude = [ "crypto/fipsmodule/aes/aes.c" ]
include_paths = ["include"]
compiler_flags = ["-Wno-error"]

[[platform_fixup.'cfg(all(target_arch = "x86_64", target_os = "windows"))'.buildscript]]
[platform_fixup.'cfg(all(target_arch = "x86_64", target_os = "windows"))'.buildscript.prebuilt_cxx_library]
name = "ring-asm-windows-x86_84"
static_libs = [ "pregenerated/*x86_64*-nasm.obj" ]
