version: "3"
services:
  pinga:
    volumes:
      - "/etc/dev.encryption.key:/run/pinga/cyclone_encryption.key:ro"
  sdf:
    volumes:
      - "/etc/dev.encryption.key:/run/sdf/cyclone_encryption.key:ro"
  veritech:
    volumes:
      - "/etc/dev.decryption.key:/run/cyclone/decryption.key:ro"
  otel:
    env_file:
      - "/etc/honeycomb_env"
