[package]
name = "si"
version = "0.1.0"
authors = ["System Initiative Inc. <media@systeminit.com>"]
edition = "2021"
rust-version = "1.69"

[[bin]]
name = "si"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
color-eyre = { workspace = true }
derive_builder = { workspace = true }
serde_json = { workspace = true }
si-cli = { path = "../../lib/si-cli" }
si-posthog = { path = "../../lib/si-posthog-rs" }
strum = { workspace = true }
telemetry-application = { path = "../../lib/telemetry-application-rs" }
tokio = { workspace = true }
