[package]
name = "sdf"
version = "0.1.0"
edition = "2021"
rust-version = "1.64"
publish = false

[[bin]]
name = "sdf"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
color-eyre = { workspace = true }
nats-multiplexer = { path = "../../lib/nats-multiplexer" }
sdf-server = { path = "../../lib/sdf-server" }
si-std = { path = "../../lib/si-std" }
telemetry-application = { path = "../../lib/telemetry-application-rs" }
tokio = { workspace = true }
tokio-util = { workspace = true }
