[package]
name = "edda"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "edda"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
edda-server = { path = "../../lib/edda-server" }
innit-client = { path = "../../lib/innit-client" }
si-service = { path = "../../lib/si-service" }

[build-dependencies]
si-service-build = { path = "../../lib/si-service-build" }
