[package]
name = "veritech"
version = "0.1.0"
edition = "2021"
rust-version = "1.64"
publish = false

[[bin]]
name = "veritech"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
color-eyre = { workspace = true }
telemetry-application = { path = "../../lib/telemetry-application-rs" }
tokio = { workspace = true }
veritech-server = { path = "../../lib/veritech-server" }
