[package]
name = "bedrock"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
bedrock-server = { path = "../../lib/bedrock-server" }
clap = { workspace = true }
si-service = { path = "../../lib/si-service" }

[build-dependencies]
si-service-build = { path = "../../lib/si-service-build" }
