[package]
name = "si-external-api-gateway"
version = "0.1.0"
authors = ["Adam Jacob <adam@systeminit.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.6"
prost-derive = "0.6"
serde = { version = "1.0", features = ["derive"] }
tonic = "0.1"
typed-builder = "0.5"

[build-dependencies]
tonic-build = "0.1"
