---
name: ci
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-run-tests:
    runs-on: ubuntu-latest
    outputs:
      run_tests: ${{ steps.save_output.outputs.run_tests }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v35.5.5
        with:
          files_ignore: |
            bin/si-discord-bot/**
            **.md
      - name: Output
        id: save_output
        env:
          RUN_TESTS: ${{steps.changed-files.outputs.any_changed == 'true'}}
        run: |
          echo $RUN_TESTS
          echo "run_tests=$RUN_TESTS" >> $GITHUB_OUTPUT
  ci:
    timeout-minutes: 40
    needs: check-run-tests
    name: Pull Request Checks
    runs-on: self-hosted
    steps:
      # Still need at least a step
      - name: 'Skip CI run but pass'
        if: needs.check-run-tests.outputs.run_tests == 'false'
        run: echo YOLO

      - name: Git Checkout
        if: needs.check-run-tests.outputs.run_tests == 'true'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Node.js
        if: needs.check-run-tests.outputs.run_tests == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup pnpm
        if: needs.check-run-tests.outputs.run_tests == 'true'
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false
      - name: Get pnpm store directory
        if: needs.check-run-tests.outputs.run_tests == 'true'
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Setup pnpm cache
        uses: actions/cache@v3
        if: needs.check-run-tests.outputs.run_tests == 'true'
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install node dependencies
        if: needs.check-run-tests.outputs.run_tests == 'true'
        run: pnpm install --frozen-lockfile
      - name: Install Rust
        if: needs.check-run-tests.outputs.run_tests == 'true'
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Login Docker
        if: needs.check-run-tests.outputs.run_tests == 'true'
        id: login
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9 # pin@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: ci
        if: needs.check-run-tests.outputs.run_tests == 'true'
        id: ci
        run: |
          : make ci
          source /data/runners/.profile
          make \
            CI=true \
            CI_FROM_REF=${{ github.event.pull_request.base.sha }} \
            CI_TO_REF=${{ github.event.pull_request.head.sha }} \
            ci
        env:
          HONEYCOMB_TOKEN: ${{ secrets.HONEYCOMB_TOKEN }}
          RUSTC_WRAPPER: /usr/local/bin/sccache
          CARGO_INCREMENTAL: false
          SI_LOG: info,cyclone_server=warn
