---
name: ci
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'app/corp/**'
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    timeout-minutes: 30
    name: Pull Request Checks
    runs-on: self-hosted
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install node dependencies
        run: pnpm install
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Login Docker
        id: login
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9 # pin@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: ci
        id: ci
        run: |
          : make ci
          source /data/runners/.profile
          make \
            CI=true \
            CI_FROM_REF=${{ github.event.pull_request.base.sha }} \
            CI_TO_REF=${{ github.event.pull_request.head.sha }} \
            ci
        env:
          HONEYCOMB_TOKEN: ${{ secrets.HONEYCOMB_TOKEN }}
          RUSTC_WRAPPER: /usr/local/bin/sccache
          CARGO_INCREMENTAL: false
          SI_LOG: info,cyclone_server=warn
