name: promote-image

on:
  workflow_call:
    inputs:
      component_name:
        required: true
        type: string
    secrets:
      SLACKBOT_TOKEN:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  promote:
    name: Promote ${{ inputs.component_name }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - id: notify-slack
        uses: voxmedia/github-action-slack-notify-build@v1.6.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACKBOT_TOKEN }}
        with:
          channel: github-notifications
          status: executing
          color: "#ffb74d"
      - id: login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - id: promote
        name: make promote//${{ inputs.component_name }}
        run: |
          : make ${{ inputs.component_name }}
          echo "::group::Promoting image"
          make promote//${{ inputs.component_name }}
          echo "::endgroup::"
      - uses: voxmedia/github-action-slack-notify-build@v1.6.0
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACKBOT_TOKEN }}
        with:
          message_id: ${{ steps.notify-slack.outputs.message_id }}
          channel: github-notifications
          status: succeeded
          color: "#8bc34a"
      - uses: voxmedia/github-action-slack-notify-build@v1.6.0
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACKBOT_TOKEN }}
        with:
          message_id: ${{ steps.notify-slack.outputs.message_id }}
          channel: github-notifications
          status: failed
          color: "#f44336"
