[package]
name = "innitctl"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "innitctl"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
innit-client = { path = "../../lib/innit-client" }
innitctl-backend = { path = "../../lib/innitctl" }
si-service = { path = "../../lib/si-service" }
tokio = { workspace = true }
